# Базовий образ з Python + PostgreSQL
FROM python:3.10

# Установка зависимостей
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN pip install poetry
RUN poetry install --no-root

# Копируем код проекта
COPY . .

# Запускаем скрипт для заполнения базы
CMD ["poetry", "run", "python", "populate_db.py"]
